# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Arvind Kumar GS
tagline:          'Online CV'
description:      'Lead cloud engineer'
url:              https://arvindkgs.github.io
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Arvind Kumar GS'
  url:            https://twitter.com/arvind_kgs

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

disqus:
  shortname:      hydeout

google_analytics: UA-100461102-1

# Used for Hydeout's own Github page. Feel free to remove for your
# own fork.
hydeout:
  version:          4.0.4
  repo:             https://github.com/fongandrew/hydeout

github: arvindkgs
stackoverflow: 355097/arvindkgs
twitter: arvind_kgs
linkedin: in/arvindkumargs
email: contact@arvindkgs.com
blog: https://blogs.oracle.com/author/arvind-kumargs

remote_theme: fongandrew/hydeout
